### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by dogi** [treehouses/builder#295]
- [x] [move to .travis](https://github.com/treehouses/builder/issues/294)
- [x] [rename to builder](https://github.com/treehouses/builder/issues/268)
- [x] [rename apt sources](https://github.com/treehouses/builder/issues/297)
- [x] [new sshkeys](https://github.com/treehouses/builder/issues/222)
